# Copyright 2018 Naglis Jonaitis
# License AGPL-3 or later (https://www.gnu.org/licenses/agpl).

import base64

# pylint: disable=missing-import-error
from cryptography import x509
from cryptography.hazmat.backends import default_backend
# pylint: enable=missing-import-error

from odoo import api, fields, models


class IMASClientCert(models.Model):
    _name = 'imas.client.cert'
    _description = 'i.MAS Client Certificate'

    name = fields.Char(
        size=32,
        required=True,
    )
    company_id = fields.Many2one(
        comodel_name='res.company',
        ondelete='cascade',
        default=lambda self: self.env.user.company_id,
    )
    active = fields.Boolean(
        default=True,
    )
    private_key_file = fields.Binary(
        string='Private Key File',
        required=True,
        copy=False,
        groups='base.group_system',
    )
    is_protected = fields.Boolean(
        string='Password Protected',
        help='Indicates whether the certificate is password protected.',
    )
    password = fields.Char(
        copy=False,
        help='Private key password',
        groups='base.group_system',
    )
    certificate_file = fields.Binary(
        string='Certificate',
        help='Client certificate which was generated by VMI',
        copy=False,
        required=True,
    )

    @api.multi
    @api.constrains('certificate_file')
    def _check_certificate_file(self):
        backend = default_backend()
        for rec in self:
            x509.load_der_x509_certificate(
                base64.b64decode(rec.certificate_file),
                backend,
            )

    @api.onchange('password')
    def _onchange_password(self):
        self.update({
            'is_protected': bool(self.password),
        })
